/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "first": string;
        "last": string;
    }
    interface MyTest {
    }
    interface TestTestTest {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyTestElement extends Components.MyTest, HTMLStencilElement {
    }
    var HTMLMyTestElement: {
        prototype: HTMLMyTestElement;
        new (): HTMLMyTestElement;
    };
    interface HTMLTestTestTestElement extends Components.TestTestTest, HTMLStencilElement {
    }
    var HTMLTestTestTestElement: {
        prototype: HTMLTestTestTestElement;
        new (): HTMLTestTestTestElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-test": HTMLMyTestElement;
        "test-test-test": HTMLTestTestTestElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface MyTest {
    }
    interface TestTestTest {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-test": MyTest;
        "test-test-test": TestTestTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-test": LocalJSX.MyTest & JSXBase.HTMLAttributes<HTMLMyTestElement>;
            "test-test-test": LocalJSX.TestTestTest & JSXBase.HTMLAttributes<HTMLTestTestTestElement>;
        }
    }
}
